### ISSUE TITLE
alembic fails

### ISSUE THREAD

**Issue by crchemist** [crchemist/cit#139]
```
env)➜  cit git:(master) alembic upgrade head
Traceback (most recent call last):
  File "/home/crchemist/projects/cit/env/bin/alembic", line 9, in <module>
    load_entry_point('alembic==0.6.5', 'console_scripts', 'alembic')()
  File "/home/crchemist/projects/cit/env/local/lib/python2.7/site-packages/alembic/config.py", line 298, in main
    CommandLine(prog=prog).main(argv=argv)
  File "/home/crchemist/projects/cit/env/local/lib/python2.7/site-packages/alembic/config.py", line 293, in main
    self.run_cmd(cfg, options)
  File "/home/crchemist/projects/cit/env/local/lib/python2.7/site-packages/alembic/config.py", line 279, in run_cmd
    **dict((k, getattr(options, k)) for k in kwarg)
  File "/home/crchemist/projects/cit/env/local/lib/python2.7/site-packages/alembic/command.py", line 125, in upgrade
    script.run_env()
  File "/home/crchemist/projects/cit/env/local/lib/python2.7/site-packages/alembic/script.py", line 203, in run_env
    util.load_python_file(self.dir, 'env.py')
  File "/home/crchemist/projects/cit/env/local/lib/python2.7/site-packages/alembic/util.py", line 212, in load_python_file
    module = load_module_py(module_id, path)
  File "/home/crchemist/projects/cit/env/local/lib/python2.7/site-packages/alembic/compat.py", line 58, in load_module_py
    mod = imp.load_source(module_id, path, fp)
  File "alembic/env.py", line 70, in <module>
    run_migrations_online()
  File "alembic/env.py", line 53, in run_migrations_online
    poolclass=pool.NullPool)
  File "/home/crchemist/projects/cit/env/local/lib/python2.7/site-packages/sqlalchemy/engine/__init__.py", line 407, in engine_from_config
    url = options.pop('url')
KeyError: 'url'
```

**Comment by IvannaBesarab** [comment]
+
