### ISSUE TITLE
migration fails

### ISSUE THREAD

**Issue by crchemist** [crchemist/cit#165]
```
(env)➜  cit git:(master) alembic upgrade head          
INFO  [alembic.migration] Context impl PostgresqlImpl.
INFO  [alembic.migration] Will assume transactional DDL.
INFO  [alembic.migration] Running upgrade 1ef4a5337a -> eac750d860b, adding user/organization relationship table
Traceback (most recent call last):
  File "/home/crchemist/projects/cit/env/bin/alembic", line 9, in <module>
    load_entry_point('alembic==0.7.6', 'console_scripts', 'alembic')()
  File "/home/crchemist/projects/cit/env/local/lib/python2.7/site-packages/alembic/config.py", line 439, in main
    CommandLine(prog=prog).main(argv=argv)
  File "/home/crchemist/projects/cit/env/local/lib/python2.7/site-packages/alembic/config.py", line 433, in main
    self.run_cmd(cfg, options)
  File "/home/crchemist/projects/cit/env/local/lib/python2.7/site-packages/alembic/config.py", line 416, in run_cmd
    **dict((k, getattr(options, k)) for k in kwarg)
  File "/home/crchemist/projects/cit/env/local/lib/python2.7/site-packages/alembic/command.py", line 165, in upgrade
    script.run_env()
  File "/home/crchemist/projects/cit/env/local/lib/python2.7/site-packages/alembic/script.py", line 390, in run_env
    util.load_python_file(self.dir, 'env.py')
  File "/home/crchemist/projects/cit/env/local/lib/python2.7/site-packages/alembic/util.py", line 243, in load_python_file
    module = load_module_py(module_id, path)
  File "/home/crchemist/projects/cit/env/local/lib/python2.7/site-packages/alembic/compat.py", line 79, in load_module_py
    mod = imp.load_source(module_id, path, fp)
  File "alembic/env.py", line 80, in <module>
    run_migrations_online()
  File "alembic/env.py", line 75, in run_migrations_online
    context.run_migrations()
  File "<string>", line 7, in run_migrations
  File "/home/crchemist/projects/cit/env/local/lib/python2.7/site-packages/alembic/environment.py", line 738, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/home/crchemist/projects/cit/env/local/lib/python2.7/site-packages/alembic/migration.py", line 309, in run_migrations
    step.migration_fn(**kw)
  File "/home/crchemist/projects/cit/alembic/versions/eac750d860b_adding_user_organization_relationship_.py", line 27, in upgrade
    sa.PrimaryKeyConstraint('user_id', 'organization_id'))
  File "/home/crchemist/projects/cit/env/local/lib/python2.7/site-packages/sqlalchemy/sql/schema.py", line 374, in __new__
    schema = metadata.schema
  File "/home/crchemist/projects/cit/env/local/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 728, in __getattr__
    key)
AttributeError: Neither 'Column' object nor 'Comparator' object has an attribute 'schema'
```

**Comment by Olexbaiko** [comment]
+
